// apps/dashboard/src/pages/GenerationForecast.tsx
﻿/*
 * Proprietary (c) Ryan Walsh / Walsh Tech Group
 * All rights reserved. Professional preview only.
 */

import { useState } from 'react'
import axios from 'axios'
import {
  Alert,
  Box,
  Button,
  Card,
  CardContent,
  FormControl,
  InputLabel,
  MenuItem,
  Select,
  TextField,
  Typography,
} from '@mui/material'
import { BarChart } from '@mui/x-charts/BarChart'

type ForecastResult = {
  p10_kw: number
  p50_kw: number
  p90_kw: number
}

export default function GenerationForecast() {
  const [result, setResult] = useState<ForecastResult | null>(null)
  const [loading, setLoading] = useState(false)
  const [error, setError] = useState<string | null>(null)
  const [windSpeed, setWindSpeed] = useState('8')
  const [capacity, setCapacity] = useState('2000')
  const [assetType, setAssetType] = useState('wind_turbine')
  const [ghi, setGhi] = useState('700')

  const runForecast = async () => {
    setLoading(true)
    setError(null)
    try {
      const payload: Record<string, number | string> = {
        site_id: 'demo_site',
        asset_type: assetType,
        capacity_kw: Number(capacity),
      }
      if (assetType === 'wind_turbine') payload.wind_speed_mps = Number(windSpeed)
      if (assetType === 'solar_inverter') {
        payload.ghi_wm2 = Number(ghi)
        payload.temperature_c = 25
      }
      const r = await axios.post('/api/v1/forecasts/site', payload)
      setResult(r.data)
    } catch {
      setResult(null)
      setError('Forecast unavailable')
    }
    setLoading(false)
  }

  const chartData = result ? [result.p10_kw, result.p50_kw, result.p90_kw] : []
  const spread = result ? result.p90_kw - result.p10_kw : 0

  return (
    <Box className="gp-grid">
      <Typography variant="h5" sx={{ fontWeight: 800 }}>Forecast</Typography>

      <Card variant="outlined">
        <CardContent>
          <Box sx={{ display: 'grid', gridTemplateColumns: { xs: '1fr', md: 'repeat(5, minmax(0, 1fr))' }, gap: 1.5, alignItems: 'end' }}>
            <FormControl size="small">
              <InputLabel>asset_type</InputLabel>
              <Select
                label="asset_type"
                value={assetType}
                onChange={(e) => setAssetType(e.target.value)}
              >
                <MenuItem value="wind_turbine">wind_turbine</MenuItem>
                <MenuItem value="solar_inverter">solar_inverter</MenuItem>
              </Select>
            </FormControl>

            <TextField size="small" label="capacity_kw" type="number" value={capacity} onChange={(e) => setCapacity(e.target.value)} />

            {assetType === 'wind_turbine' ? (
              <TextField size="small" label="wind_speed_mps" type="number" value={windSpeed} onChange={(e) => setWindSpeed(e.target.value)} />
            ) : (
              <TextField size="small" label="ghi_wm2" type="number" value={ghi} onChange={(e) => setGhi(e.target.value)} />
            )}

            <Box sx={{ display: 'flex', justifyContent: { xs: 'stretch', md: 'flex-start' } }}>
              <Button variant="contained" onClick={runForecast} disabled={loading} fullWidth>
                {loading ? 'running' : 'run'}
              </Button>
            </Box>
          </Box>
        </CardContent>
      </Card>

      {error && <Alert severity="error">{error}</Alert>}

      {result && (
        <>
          <Box sx={{ display: 'grid', gridTemplateColumns: { xs: 'repeat(2, minmax(0, 1fr))', md: 'repeat(4, minmax(0, 1fr))' }, gap: 1.5 }}>
            <Card variant="outlined"><CardContent><Typography variant="caption">p10_kw</Typography><Typography variant="h5">{Math.round(result.p10_kw)}</Typography></CardContent></Card>
            <Card variant="outlined"><CardContent><Typography variant="caption">p50_kw</Typography><Typography variant="h5">{Math.round(result.p50_kw)}</Typography></CardContent></Card>
            <Card variant="outlined"><CardContent><Typography variant="caption">p90_kw</Typography><Typography variant="h5">{Math.round(result.p90_kw)}</Typography></CardContent></Card>
            <Card variant="outlined"><CardContent><Typography variant="caption">band_kw</Typography><Typography variant="h5">{Math.round(spread)}</Typography></CardContent></Card>
          </Box>

          <Card variant="outlined">
            <CardContent>
              <Typography variant="subtitle1" sx={{ fontWeight: 700, mb: 1 }}>forecast_distribution_kw</Typography>
              <BarChart
                height={280}
                xAxis={[{ scaleType: 'band', data: ['p10', 'p50', 'p90'] }]}
                series={[{ data: chartData, label: 'kw' }]}
                margin={{ left: 45, right: 10, top: 20, bottom: 35 }}
              />
            </CardContent>
          </Card>
        </>
      )}
    </Box>
  )
}

// apps/dashboard/src/pages/GenerationForecast.vue
<template>
  <section class="page-grid">
    <h1>Generation Forecast</h1>

    <article class="glass-panel panel form-grid">
      <label>
        Asset Type
        <select v-model="assetType" class="console-input">
          <option value="wind_turbine">wind_turbine</option>
          <option value="solar_inverter">solar_inverter</option>
        </select>
      </label>
      <label>
        Capacity kW
        <input v-model.number="capacity" type="number" class="console-input" />
      </label>
      <label v-if="assetType === 'wind_turbine'">
        Wind Speed m/s
        <input v-model.number="windSpeed" type="number" class="console-input" />
      </label>
      <label v-else>
        GHI W/m2
        <input v-model.number="ghi" type="number" class="console-input" />
      </label>
      <button class="nav-link" @click="runForecast">Run</button>
    </article>

    <article v-if="result" class="glass-panel panel">
      <div class="results-grid">
        <StatCard label="P10" :value="Math.round(result.p10_kw) + ' kW'" />
        <StatCard label="P50" :value="Math.round(result.p50_kw) + ' kW'" />
        <StatCard label="P90" :value="Math.round(result.p90_kw) + ' kW'" />
        <StatCard label="Band" :value="Math.round(result.p90_kw - result.p10_kw) + ' kW'" />
      </div>
      <Bar :data="chartData!" :options="chartOptions" class="chart" />
    </article>

    <p v-if="error" class="error">{{ error }}</p>
  </section>
</template>

<script setup lang="ts">
import axios from 'axios'
import { ref, computed } from 'vue'
import { Bar } from 'vue-chartjs'
import {
  Chart as ChartJS,
  CategoryScale,
  LinearScale,
  BarElement,
  Tooltip,
  Legend,
} from 'chart.js'
import StatCard from '../components/StatCard.vue'

ChartJS.register(CategoryScale, LinearScale, BarElement, Tooltip, Legend)

type ForecastResult = { p10_kw: number; p50_kw: number; p90_kw: number }

const assetType = ref<'wind_turbine' | 'solar_inverter'>('wind_turbine')
const capacity = ref(2000)
const windSpeed = ref(8)
const ghi = ref(700)
const result = ref<ForecastResult | null>(null)
const error = ref('')

async function runForecast() {
  error.value = ''
  result.value = null
  try {
    const payload: Record<string, number | string> = {
      site_id: 'demo_site',
      asset_type: assetType.value,
      capacity_kw: capacity.value,
    }
    if (assetType.value === 'wind_turbine') payload.wind_speed_mps = windSpeed.value
    if (assetType.value === 'solar_inverter') {
      payload.ghi_wm2 = ghi.value
      payload.temperature_c = 25
    }
    const response = await axios.post('/api/v1/forecasts/site', payload)
    result.value = response.data
  } catch {
    error.value = 'Forecast unavailable'
  }
}

const chartData = computed(() => {
  if (!result.value) return null
  return {
    labels: ['P10', 'P50', 'P90'],
    datasets: [{
      label: 'kW',
      data: [result.value.p10_kw, result.value.p50_kw, result.value.p90_kw],
      backgroundColor: [
        'rgba(80, 190, 255, 0.5)',
        'rgba(80, 190, 255, 0.8)',
        'rgba(80, 190, 255, 0.5)',
      ],
    }],
  }
})

const chartOptions = {
  responsive: true,
  maintainAspectRatio: false,
  plugins: { legend: { display: false } },
  scales: {
    x: { ticks: { color: '#91a8b8' }, grid: { color: 'rgba(80,190,255,0.08)' } },
    y: { ticks: { color: '#91a8b8' }, grid: { color: 'rgba(80,190,255,0.08)' } },
  },
}
</script>

<style scoped>
.page-grid { display: grid; gap: 14px; }
h1 { margin: 0; font-size: 28px; }
.panel { padding: 14px; }
.form-grid { display: grid; grid-template-columns: repeat(auto-fit, minmax(180px, 1fr)); gap: 10px; align-items: end; }
label { display: grid; gap: 6px; color: #91a8b8; }
.results-grid { display: grid; grid-template-columns: repeat(auto-fit, minmax(140px, 1fr)); gap: 12px; margin-bottom: 14px; }
.chart { height: 220px; }
.error { color: #ff7043; }
</style>
